api_platform:
    enable_fos_user: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    title: 'API Escape Game Corp.'
    description: "Service web pour gerer les informations de EGC"
    version: 'Beta 1.0'
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
