security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
 
    firewalls:
        # api_login:
        #     pattern: ^/auth/login
        #     stateless: true
        #     anonymous: true
        #     provider: fos_userbundle
        #     json_login:
        #         provider: fos_userbundle
        #         check_path:               /auth/login
        #         success_handler:          lexik_jwt_authentication.handler.authentication_success
        #         failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        main:
            pattern: ^/
            provider: fos_userbundle
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            
    access_control:
        - { path: ^/tokens, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ ROLE_ADMIN ] }
